### ISSUE TITLE
Publish doesn't work.

### ISSUE THREAD

**Issue by Sami-L** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#10]
When Trying to publish the project in Visual Studio 2017, it gives the following error:

**Error**: **Can't resolve 'bootswatch/flatly/bootstrap.css'** in 'C:\Projects\TestMakerFree'	TestMakerFree	Module not found 0

Error: The command "**node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" exited with code 2**.	  TestMakerFree   C:\Projects\TestMakerFree\TestMakerFree.csproj	70

I cannot find where it points to 'bootswatch/flatly/bootstrap.css'

**Comment by Darkseal** [comment]
Hello and thank you for purchasing the book.

I would suggest you to check this issue and see if it applies to your scenario:

https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/7

Please let me know.

**Comment by Sami-L** [comment]
Added "bootswatch": "3.3.7" to package.json as suggested [in the link you provided above](https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/7) and it worked.
