### ISSUE TITLE
Impossible to Create First Project

### ISSUE THREAD

**Issue by sipi41** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#12]
I'm sorry to bother you but I tried to re-create your steps and after 5 hours here, I can't make this thing work! I had to come to your files and even, when I did run your project, it came to an error... I'm frustrated... I think I did take care of each step carefully... tried to use the latest versions, bad! tried to use your version, bad! tried and tried and tried! 
![screenshot1](https://user-images.githubusercontent.com/688562/34704337-21eaf64c-f4be-11e7-8e02-73a7e0867f41.png)

I need some help, otherwise I will drop this book and claim my money back... I understand that you cant edit the pdf file or the physical book BUT at least you should have an updated video or step by step on how to start a project from 0, then update angular 4 to 5... because the only way I was able to make it work is by taking your code and run the 2 .bat files you have there... but I would like to know how to do it from scratch... I tried to run the command npm update also with no success... how did you make this work???

**Comment by Belka383** [comment]
@sipi41 Good afternoon! Do not worry, everyone faced such problems! Do not let go of your hands. Let's start in order. Do you get to run the original project with the Angular template without making any changes?

**Comment by sipi41** [comment]
Thanks Belka383 for your prompt answer.  These are the steps I made:

1. Updated the Templates as you said on your book using "**dotnet new --install Microsoft.AspNetCore.SpaTemplates::***"
2. Installed the latest version of Node.js 9.x
3. Created the project and run the example.

The problem is that the project > dependencies > npm show we are using version 4.2.5, and we should update to 5, right? after hours here, the only thing that seems to work is a guide at [https://www.codeproject.com/Articles/1221503/Angular-and-NET-Core-with-Visual-Studio](https://www.codeproject.com/Articles/1221503/Angular-and-NET-Core-with-Visual-Studio) but my question is... is this the proper way to do it? as it perform so many changes to config files in order to make it work... 

Also, after follow the update guide, this is the result after running **ncu -u** twice:

![screenshot2](https://user-images.githubusercontent.com/688562/34726157-d7d95fe8-f518-11e7-8915-8c6ca92ffedc.png)

this means that I have successfully updated all my npm packages to the latest version, right?, is this enough? because when I come to the solution explorer and check dependencies >> npm >> what I see is this:

![screenshot3](https://user-images.githubusercontent.com/688562/34726293-36eab518-f519-11e7-850c-209ef095e277.png)

it seems like it updated to the latest version but shows 4.2.5... please help! 

is there a way for you to record the right steps in a video or a guide, using the latest VS version? a brief explanation on the proper commands to use would be ideal, at least for newbies like me... :-)  Thank you!

**Comment by Belka383** [comment]
That's where you're wrong: step 2 - Installed the latest version of Node.js 9.x. Required version NodeJS 6.9.0. Read the book carefully: page 24.

Good luck!

**Comment by sipi41** [comment]
You did start really good, but ended really bad!... good luck? I uninstalled the latest version and tried to download the version you recommend, this is what I have:
![screenshot4](https://user-images.githubusercontent.com/688562/34727301-279763f6-f51c-11e7-88d5-f90e178f97be.png)
now what? a black screen with a command prompt? no installer at all... what to do with that? if you are recommending a version you should explain how to... instead of "good luck"... I will need that if I can make your examples work! need real help here, please.

**Comment by Belka383** [comment]
@sipi41 I do not understand the reason for your aggression. A good programmer will try to look for solutions on the Internet, rather than crying at forums and all the more in the author's repository.

To make you feel ashamed, I will record you the video on the first part of "Getting Ready". I'll post it a little later

**Comment by sipi41** [comment]
aggression? crying? your mama is crying! very disrespectful! first you should work with the latest versions as soon as possible, second, I did ask you if the URL I provided was a possible solution... was it?

I think maybe is not the right time to study version 5... everybody on the "forums" talk about v4... this is the first book I see trying to deal with v5... probably is better to wait a little longer.

**Comment by Belka383** [comment]
@sipi41 1) step: make sure that the following tools are installed
![image](https://user-images.githubusercontent.com/10748155/34758162-e3ef1844-f5e6-11e7-88f3-6b29b42d16bf.png)
2) create a project: 
![image](https://user-images.githubusercontent.com/10748155/34758198-173223ae-f5e7-11e7-8a52-08320ee1645b.png)
![image](https://user-images.githubusercontent.com/10748155/34758204-1d7031d4-f5e7-11e7-9b49-0fa303f10c9c.png)
3) close project
4) open "package.json" file
5) paste: 
{
  "name": "MyApp",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "5.0.2",
    "@angular/common": "5.0.2",
    "@angular/compiler": "5.0.2",
    "@angular/compiler-cli": "5.0.2",
    "@angular/core": "5.0.2",
    "@angular/forms": "5.0.2",
    "@angular/http": "5.0.2",
    "@angular/platform-browser": "5.0.2",
    "@angular/platform-browser-dynamic": "5.0.2",
    "@angular/platform-server": "5.0.2",
    "@angular/router": "5.0.2",
    "@ngtools/webpack": "1.8.2",
    "@types/webpack-env": "1.13.2",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "3.0.1",
    "aspnet-webpack": "2.0.1",
    "awesome-typescript-loader": "3.4.0",
    "bootstrap": "3.3.7",
    "bootswatch": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.7",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "1.1.5",
    "html-loader": "0.5.1",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.7",
    "preboot": "5.1.7",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "style-loader": "0.19.0",
    "to-string-loader": "1.1.5",
    "typescript": "2.4.2",
    "url-loader": "0.6.2",
    "webpack": "2.6.1",
    "webpack-hot-middleware": "2.20.0",
    "webpack-merge": "4.1.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3"
  }
}
!!! name = your name progect
6) open "tsconfig.json" file
7) paste:
{
  "compilerOptions": {
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "strict": true,
    "lib": [ "es6", "dom" ],
    "types": [ "webpack-env" ]
  },
  "exclude": [ "bin", "node_modules" ],
  "atom": { "rewriteTsconfig": false },
  "angularCompilerOptions": {
    "strictMetadataEmit": true
  }
}
8) insert files into the root "update-npm.bat", "update-webpack.bat"
![image](https://user-images.githubusercontent.com/10748155/34758607-67e21132-f5e8-11e7-93b1-9482201c34ad.png)
9) run "update-npm.bat" file
10) Updating the webpack.config.js file: 
 10.1 const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
 10.2 [...]
module: {
    rules: [
        { test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/, [...]
11) Patching the webpack.config.vendor.js file:
new webpack.ContextReplacementPlugin(/\@angular(\\|\/)core(\\|\/)esm5/, path.join(__dirname, './ClientApp')), // Workaround for https://github.com/angular/angular/issues/20357
12) 9) run "update-webpack.bat" file 

13) open your progect in VS 
14) run

15) Use and study with pleasure
16) Good luck!

**Comment by greg-bowie** [comment]
Hi,

Not sure if this issue is still open for comment or not. Thanks for all the efforts @Belka383 but I'm afraid even after following the steps above I'm getting an error when running the app:

![image](https://user-images.githubusercontent.com/35299703/34775820-68b90948-f60c-11e7-9975-f3f8017bdf5f.png)

I can confirm that Node version is 6.9.0:

![image](https://user-images.githubusercontent.com/35299703/34775791-4f87928c-f60c-11e7-99dd-3823635c48b5.png)

.NET Core version is 2.1.3:

![image](https://user-images.githubusercontent.com/35299703/34775840-7efdf4d4-f60c-11e7-8d37-2f2cb80b2edd.png)

I copy and pasted your package.json file, but image below in case something is obviously missing:

![image](https://user-images.githubusercontent.com/35299703/34775886-a8102d4c-f60c-11e7-8086-a9e816e7dda7.png)
![image](https://user-images.githubusercontent.com/35299703/34775893-b0798a78-f60c-11e7-80ab-6873dd75f304.png)
![image](https://user-images.githubusercontent.com/35299703/34775904-b8c3c75c-f60c-11e7-8a1c-63ef720714a6.png)

My tsconfig.json file looks as follows:

![image](https://user-images.githubusercontent.com/35299703/34775922-d03d854e-f60c-11e7-9217-3cb443e0aee3.png)

I've run npm update at this stage.

My webpack.config.js looks as follows (relevant changes):

![image](https://user-images.githubusercontent.com/35299703/34775972-040c70f6-f60d-11e7-9764-d2fc2b4dc07c.png)

And my webpack.config.vendor.js looks as follows (relevant changes):

![image](https://user-images.githubusercontent.com/35299703/34775991-14e2a77e-f60d-11e7-91d5-7e2f1f4b556a.png)


I've then run the 'node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js' command, as per the book Page 49.

Any suggestions at this stage?

Many thanks,
Greg

**Comment by Belka383** [comment]
Colleagues, I noticed that for some reason the main-server.js file ceased to be generated

**Comment by Belka383** [comment]
Previously, this file was generated after the update webpack

**Comment by greg-bowie** [comment]
Thanks @Belka383 - where would that file reside in the project files?

**Comment by Belka383** [comment]
@greg-bowie \ClientApp\dist

**Comment by greg-bowie** [comment]
@Belka383 Thanks again. I have checked my folder, and I do have a main-server.js file. It was generated about the time I last did a build?

**Comment by sipi41** [comment]
I think the best idea here is not to try to patch all this mess... I think somebody at MS or anybody who is completely aware of the topic, should create a template that works from 0... I see you trying to do this, and see other people trying to do something totally different (ex: https://www.codeproject.com/Articles/1221503/Angular-and-NET-Core-with-Visual-Studio) and I sincerely don't know who is right...

**Comment by Belka383** [comment]
@sipi41 
About the command line - you need to install one and the assembly in accordance with the bit depth:

![image](https://user-images.githubusercontent.com/10748155/34779300-dc1ec02a-f630-11e7-8c91-b7cda6c67f36.png)

**Comment by Darkseal** [comment]
Hello,

I'll do my best to address all your questions:

-------------------------------------------------------------------------------------------------------------

@sipi41 :  I can personally guarrantee that the code is working with any version of Angular, NodeJS and ASP.NET Core available today, but you have to perform some minor tweaks required by the (seldomly) breaking changes that these frameworks unavoidably bring. You can't really expect to update everything and hope that everything will work without being aware of what you're updating and what the new stuff will bring: such kind of "hassle-free" update is for operating systems and security patches, not for development frameworks where new versions will often bring more features and breaking changes. I wrote an entire book paragraph about such topic (Chapter 1: Disclaimer-Do (not) try this at home) which I strongly suggest you to read.

If you really do consider yourself a "newbie" (like you said above) and/or don't want to perform these tweaks, you should really stick to the versions/builds given by the book: that has nothing to do with "being afraid" of updates, it just means that you still have to practice the basics before being able to adjust your code with the various changelogs. There is nothing wrong with it and it doesn't mean you will have to stick to the old versions forever... Just enjoy the learning phase and don't rush it.

All that said, if I were you, I would do the following:

1) Install NodeJS 6.9.0 (the assembly that match your CPU)
2) Get the updated GitHub project and save it to your Hard Drive
3) Open the `TestMakerFreeWebApp_UpdatedProject.sln` file 
4) Execute the `npm-update.bat` and `update-webpack.bat` file
5) Launch the project in debug mode and see what happens

It takes 2 minutes total and it will clearly show if the code is working or not. If it does, you can carefully compare the project downloaded from GitHub with yours and understand the difference. If it doesn't, we will gladly help you to get it running.


-------------------------------------------------------------------------------------------------

@Belka383 : the `ClientApp/dist/main-server.js` file is generated whenever you run the project in debug mode or publish your project anywhere, as per the following `.csproj` file settings:

```

[...
  <Target Name="DebugRunWebpack" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('wwwroot\dist') ">

[...]

    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js" />
    <Exec Command="node node_modules/webpack/bin/webpack.js" />
  </Target>

[...]

  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec Command="npm install" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />
    <Exec Command="node node_modules/webpack/bin/webpack.js --env.prod" />

[...]
```

**Comment by greg-bowie** [comment]
@Darkseal Thanks for the updates. I followed Steps 1-5 have managed to get the page to load (albeit with commenting out the SeedData call (line 37, Program.cs)).

Started to look through the differences between packages.json, tsconfig.json and the webpack.config.js / vendor.js - unfortunately they're fairly considerably, and indeed some of the files don't have any of the changes mentioned to implement in the book. Copying the new file contents across from the working project doesn't rectify the situation - but I feel like its probably worth creating it from scratch (again!) and implementing the text from the 'working' project at the appropriate stage. I'll do this tomorrow and report back.

**Comment by greg-bowie** [comment]
Decided to give it a shout tonight. Creating the project from scratch, copying and pasting file content from packages.json, tsconfig.json, webpack.config.js and webpack.config.vendor.js - copying and pasting the batch update utilities and running those from the command line.

Hitting F5 and the following error message is displayed:

![image](https://user-images.githubusercontent.com/35299703/34796135-790dc44c-f64c-11e7-865c-d5ba0f581294.png)

Is anyone able to create the project, in a running state, as its meant to be at the end of Chapter 1 of the book? The 'UpdatedProject' downloaded earlier appears significantly different and contains a lot more functionality that I'd expect for the end of Chapter 1.

**Comment by sipi41** [comment]
as I said in my previous messages, I did create one following the steps in https://www.codeproject.com/Articles/1221503/Angular-and-NET-Core-with-Visual-Studio

**Comment by Darkseal** [comment]
@greg-bowie and @sipi41, I just did the following:

- Got the `TestMakerFreeWebApp_Chapter_01.sln` file from GitHub
- Set up `TestMakerFreeWebApp_Chapter_01_Part02` as Startup Project
- Executed the `npm-update.bat` and `update-webpack.bat `file
- Launched the project in debug mode 

You can see the results in the attached screenshots. If you get any "Internal Server Error", please try disabling SSR as explained in Issue #9 (or just hit F5 since SSR gets disabled on reload) and you'll be set.

@greg-bowie , kindly notice that there are ABSOLUTELY NO DIFFERENCES between TestMakerFreeWebApp_Chapter_01_Part02 and the code described in book Chapter 01: conversely, if you compare book's Chapter 01 with the `TestMakerFreeWebApp_UpdatedProject`, which is meant to be used BEYOND CHAPTER 10, you will find a lot of differences... basically, everything that's explained and coded within the whole book.

**IMPORTANT NOTE**: Since everyone seems to be stuck by issue #9 , which is understandably not read by (almost) anyone and basically a MS fault more than a book fault, I'm just removing SSR alltogether from GitHub.

**Comment by Belka383** [comment]
And again, hello everyone! Found a good article 👍: 
https://neelbhatt40.wordpress.com/2017/12/21/create-angular-5-application-using-net-core-2-0-template-in-visual-studio-2017/

**Comment by Belka383** [comment]
@sipi41, @greg-bowie  It turned out to create a project on Angular 5!
Instruction:
1 step:
Prerequisite:
    Visual studio 2017 
    .Net Core 2.0 SDK Version 2.1.4
    !!! Node.js Version 6.9.0 !!!
2 step: open: https://neelbhatt40.wordpress.com/2017/12/21/create-angular-5-application-using-net-core-2-0-template-in-visual-studio-2017/ 
and add Angular 5 template to VS 2017
3 step: create project use template Angular 5TF
4 step: open file 'packaje.json' and replace all (20) symbol'^' to '~'. Save changes, close project
5 step: cype file 'update-npm.bat' and 'update-webpack.bat'
6 step: run 'update-npm.bat' 
7 step: run 'update-webpack.bat'
8 step: open project
9 press F5 and we see that it works!

**Comment by asmtony** [comment]
Firstly, I would like to say thank you to the author for writing this book. I think it is exactly what I need, still reading though. There are a lot of moving parts around angular and getting them to work in VS in our fast-moving world was always going to attract criticism. Thought I would add my 2 cents though. 

Yesterday I faced the same issue as others have before me. I could not get the first example to build. This needed to be resolved.

After around 12 hours or reading and failed projects this is what I think needs to be done. My machine before I started was just the most up-to-date version of VS 2017 but no extras. Now my thinking was that this should mean that I do not have to install stuff. NOT TRUE. 

First thing to do is scrap the project you just created. The reason I say this is there are some things you need to do before creating it. In fact, the book actual tells you about this stuff on the next page (p. 30). Make sure you read to the end of my post before starting and the link I give you.

Second thing you must do is install the latest stable build of Node. 
Third. Get the Angular template 
Fourth. Add this line to the package.json file "postinstall": "webpack --config webpack.config.vendor.js"
I won’t reinvent the wheel telling you exactly how. Just follow the great instructions [here](https://neelbhatt40.wordpress.com/2017/12/21/create-angular-5-application-using-net-core-2-0-template-in-visual-studio-2017/)..

asmtony

**Comment by TresPatines** [comment]
After spending a couple of days trying to solve this issue, it worked to me the last post of Belka383.
Thank you very much...
