### ISSUE TITLE
NgFor only supports binding to Iterables such as Arrays

### ISSUE THREAD

**Issue by kennethbernstrom** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#13]
I have a problem in Chapter 03 when trying to iterate the sample quiz on the home page. My component look like this:

`
import { Component, Inject, OnInit } from "'@'angular/core";
import { HttpClient } from "'@'angular/common/http";

@Component({
    selector: "quiz-list",
    templateUrl: './quiz-list.component.html',
    styleUrls: ['./quiz-list.component.css']
})

export class QuizListComponent implements OnInit {
    title: string;
    selectedQuiz: Quiz;
    quizzes: Quiz[];
    http: HttpClient;
    baseUrl: string;

    constructor(http: HttpClient, @Inject('BASE_URL') baseUrl: string) {
        this.title = "Latest quizzes";
        this.baseUrl = baseUrl + "api/quiz/latest/";
        this.http = http;
    }

    ngOnInit() {
        this.http.get<Quiz[]>(this.baseUrl).subscribe(result => {
            this.quizzes = result; 
        }, error => console.error(error));
    }

    onSelect(quiz: Quiz) {
        this.selectedQuiz = quiz;
        
    }
}`

And the ngfor below is the problem (i think):

`*ngFor="let quiz of quizzes"`

The problem is that the ngFor doesnt recognize quizzes as the arraytype Quiz[] that it is. Instead it thinks of it as an undefined object. So the browser gives me this errormessage:

`ERROR Error: Cannot find a differ supporting object '[object Object]' of type 'object'. NgFor only supports binding to Iterables such as Arrays.`

I cant get by this problem because according to the new HttpClient for angular i dont have to parse data since i am setting the type in the get<Quiz[]> method. Anyone had the same problem and solved it?

**Comment by kennethbernstrom** [comment]
Oh my god, i have struggled to find the problem and then i hit me! the url that was fetching the data only fetched a single object and not an Array containing one item.

**Comment by ssack** [comment]
Please how did you fix this issue. I'm very new to Angular

**Comment by kennethbernstrom** [comment]
The issue lied in the QuizControllers Latest method and not in Angular. The httpget attribute had the num parameter set as mandatory, like this:
`[HttpGet("Latest/{num}")]`
And the Url i used to fetch data was /api/quiz/latest/ , no parameter which made the api to hit the Controllers get method instead who returns a single Quiz object instead of a a Quiz[].

I changed the HttpGet attribute to this optional num parameter
`[HttpGet("Latest/{num:int?}")]`

And then everything worked fine after that!
