### ISSUE TITLE
UpdatedProject --Can't generate default database

### ISSUE THREAD

**Issue by bruceliu2008** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#14]
The code breaks at this line in DbSeeder.
if (!dbContext.Users.Any())

I tried to call SetInitializer() in ApplicationDbContext constructor, but I can't find this method any more.
Did I miss anything else?

Thanks,
Bruce

**Comment by bruceliu2008** [comment]
Managed to fix it by adding this line:
                var dbContext = scope.ServiceProvider.GetService<ApplicationDbContext>();
                dbContext.Database.EnsureCreated(); --new line.

But still got error when trying to register a new user.

"The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_AspNetUserRoles_Users_UserId\". The conflict occurred in database \"TestMakerFree\", table \"dbo.Users\", column 'Id'.\r\nThe statement has been terminated."

After populating the Id field as follows still the same error.
            user = new ApplicationUser()
            {
                Id = Guid.NewGuid().ToString(), -- new line.
                SecurityStamp = Guid.NewGuid().ToString(),

Thanks,
Bruce

**Comment by Darkseal** [comment]
Hello @bruceliu2008 , 

The UpdatedProject is meant to go beyond Chapter 10: did you perform all the `dotnet ef `commands described in Chapter 4 up to Chapter 9? These are mandatory in order to create the DB and then update it to support the updated code.

Please let me know,

**Comment by bruceliu2008** [comment]
Thanks for the prompt reply, will try next Monday, have a good weekend.

Thanks.

**Comment by Darkseal** [comment]
Any luck with that?

**Comment by bruceliu2008** [comment]
Hi Dark,
    It works now, the problem is in this line:
await UserManager.CreateAsync(user, model.Password);
It didn't capture the return value, which will include validation results.
The root cause of the issue is that my password is too short. But the code didn't handle the validation result and proceed to create UserRole, which actually depends on a successful new user creation.

I did try to use 'dotnet ef migrations add initialcreate' and 'dotnet ef database update' to recreate the database, but the problem still exists because of the above root cause.

Thanks,
Bruce

**Comment by Darkseal** [comment]
OK, I get it. I didn't think of checking results there since it was an internal seeder but you're right, I should definitely add some checks there to ensure that the developer won't chose an insecure password even for test users (and hence fail to create them). I'll work it out as soon as I got time. Nice finding, thank you.

**Comment by macupryk** [comment]
Any luck, if so I am getting the same issue.
Let me know how you were able to fix issue?
