### ISSUE TITLE
Usage of Put and Post

### ISSUE THREAD

**Issue by Drago96** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#17]
It seems that in this book Put is used to create a new item and Post to update an existing one. From my knowledge on HTTP, shouldnt Post be used to create a new item and Put to create if doesn't exist/ update if exists? Is the reverse usage simply a preference of the author or is there more meaning behind it?

**Comment by Darkseal** [comment]
It was a mess-up during the tech review-editing: I wish I noticed sooner than that so I could fix it :) Everything will also work when using them that way, but I also strong encourage to follow the HTTP standards and use PUT to edit and POST to create: I suggest to switch the two accordingly (in Core and Angular) to adhere to the standard.

**Comment by Drago96** [comment]
Thank you for the quick answer, love the book so far.
