### ISSUE TITLE
Running the project in "older" browsers - for example, in IE 9, 10 and 11*

### ISSUE THREAD

**Issue by Belka383** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#18]
Tell me how to solve the problem of running in old browsers. How to connect a polyfills file?

**Comment by Belka383** [comment]
Solved the problem this way:
1 step: added the following lines of code to the file "boot.browser.ts":
`
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
import 'intl/locale-data/jsonp/en';
`
2 step: open PowerShell in root folder the project and run: 
->  npm install --save intl
->  npm install --save classlist.js
->  npm install --save core-js

3 step: run your project

Good luck!

**Comment by Belka383** [comment]
or created new file 'ClientApp/boot.polyfills.ts', paste the code and import in boot.browser.ts: import '../ClientApp/boot.polyfills';

**Comment by Darkseal** [comment]
Thanks for the nice enhancement: flagged the issue accordingly!
