### ISSUE TITLE
Updating the Webpack.config.js file

### ISSUE THREAD

**Issue by JByrd99** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#20]
In my Kindle Reader (browser) version (Chrome)

In the code listing for change from Angular 4 => Angular 5, there is a missing closing curly bracket/brace after the closing of the RegEx ("$/"):

This:
{ test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)**$/**,

Should be:
{ test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)**$/ }**,

Hope this helps!

Jon

**Comment by Darkseal** [comment]
Hello, are you talking of `webpack.config.js` file update in Chapter 1?

if that's so, the code should be the following:

    { test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },
