### ISSUE TITLE
Issue refreshing a page after authenticating

### ISSUE THREAD

**Issue by zzcraig** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#22]
Hi,

I'll admit, I haven't followed the entire book as I'm currently using it to implement token authentication in Angular 5, so my code isn't identical to the GitHub book.

Currently I can log in and authenticate on my app which makes a request to a controller decorated with [Authorize].  However, if I refresh this Angular page, I then get:

![image](https://user-images.githubusercontent.com/36083555/35748515-38194202-0846-11e8-8071-e8e89f73e31e.png)

If I check my console, I can see:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Http failure response for http://localhost:5001/api/SampleData/GetTests: 401 Unauthorized

Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Http failure response for http://localhost:5001/api/SampleData/GetTests: 401 Unauthorized
```

I have checked my headers and for some reason, on refresh of the page the token is not set in the header (the interceptor isn't hit at all).

However, if I go back to the app's home page and click back in to the page that requires authentication, everything works fine again.

Is this to do with the SSR bugs in Angular 5 / Core? Or have I done something else wrong.

Disabling SSR makes all these issues disappear, but it would be nice to find out what's going on and see if it's possible to fix

Thanks

**Comment by Darkseal** [comment]
As much as I'm aware of, Angular SSR still causes many odd behaviours in ASP.NET Core 2 Middleware: we just need to hope that they will fix this.
