### ISSUE TITLE
Chapter 4 Error

### ISSUE THREAD

**Issue by GarthFHenderson** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#23]
I am getting an error running the Chapter 4 Example code when I run the following command in PowerShell:
      dotnet ef migrations add "Initial" -o "Data\Migrations" 

Resulting Error:
An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. Error: Invalid object name 'Users'.
Unable to create an object of type 'ApplicationDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<ApplicationDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.

With the Error, the result is that the TestMakerFree Database is created with a single table:  
    dbo._EFMigrationsHistory

Please advise.

**Comment by JoelTipke** [comment]
Hi Garth,


I hit this same issue. The author already posted some updated source code which moves the database seeder into a different class.

See the updated code in Program.cs and Startup.cs in the github repo.

Hope this helps!

Joel


________________________________

**Comment by GarthFHenderson** [comment]
Thanks, Joel!

Works like a charm now.
