### ISSUE TITLE
QuizListComponent

### ISSUE THREAD

**Issue by TresPatines** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#25]

**Comment by angelbarranco** [comment]
Change:
` import { HttpClient } from '@angular/common/http';`
to
` import { HttpClientModule } from '@angular/common/http';`

**Comment by TresPatines** [comment]
Thanks for the help, the solution wasn't what you tell me. Anyway, thanks a lot.
Already solved. The error was in the book.

**Comment by diverjasongray** [comment]
I am getting an error when I use both:

import { HttpClient } from '@angular/common/http';

or

import { HttpClientModule } from '@angular/common/http';

Any ideas?

Thanks,

Jason
