### ISSUE TITLE
Clarification: meaning of LastModifiedDate

### ISSUE THREAD

**Issue by samiroquai** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#26]
Hi, 

Just to make sure: 
- CreatedDate is meant to be the date and time at which a Quiz was created?
- LastModifiedDate is meant to be the date and time at which a Quiz was modified for the last time?

If these are true, then when you update a Quiz (Quiz Controler, Post Method, related to issue #17 ) do you set the LastModifiedDate to the CreatedDate? (see code below)

```cs            
// properties set from server-side

quiz.LastModifiedDate = quiz.CreatedDate;
```
Shouldn't it be more like the following?
```cs            
// properties set from server-side

quiz.LastModifiedDate = DateTime.Now;
```

**Comment by Darkseal** [comment]
Yeah, definitely: that was an evident oversight. Thank you for pointing it out!
