### ISSUE TITLE
p272 - Less nested selector

### ISSUE THREAD

**Issue by samiroquai** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#27]
At page 272, you can read the following. 

```
// the &amp; char represents the current selector parent .
// in this scenario, it stands for item-list.latest .
````
Shouldn't it be quiz-list.latest instead of item-list.latest?

**Comment by Darkseal** [comment]
Hi samiroquai,

That's correct! Many thanks for pointing it out.
