### ISSUE TITLE
Quiz-list-component issue

### ISSUE THREAD

**Issue by diverjasongray** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#28]
I am experiencing a problem with the quiz list. It does not seem to like either one of the following:

import { HttpClient } from '@angular/common/http';
to
import { HttpClientModule } from '@angular/common/http';

I get a build error for both.  Went to the Google docs and it looks like the bottom is correct. But I am still getting errors. Appreciate a solution so I can continue.

**Comment by JoelTipke** [comment]
Double check your app.module.shared file: 

```
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClientModule } from '@angular/common/http';
```

And also verify you have these entries in your package.json file: 

```
    "@angular/common": "5.0.2",
    "@angular/compiler": "5.0.2",
    "@angular/compiler-cli": "5.0.2",
    "@angular/core": "5.0.2",
    "@angular/forms": "5.0.2",
    "@angular/http": "5.0.2", 
```

Different versions, which may or may not work.

**Comment by diverjasongray** [comment]
I am getting the error in both the app.module.shared.ts file as well as the
quiz-list.component.ts file. I have updated the entries you listed in the
package .json file as well.  I am not sure where else to go from here.

**Comment by Borislavsl** [comment]
Hello,  When I start Chapter 3 page 113  Testing up,  I receive the following errors:

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\node_modules\bootstrap\dist\js'
 @ ./node_modules/bootstrap/dist/js/bootstrap.js 7:100-120
 @ ./ClientApp/boot.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in ./ClientApp/boot.browser.ts
Module not found: Error: Can't resolve 'zone.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\ClientApp'
 @ ./ClientApp/boot.browser.ts 2:0-17
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:10:5 
    TS2564: Property 'selectedQuiz' has no initializer and is not definitely assigned in the constructor.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:11:5 
    TS2564: Property 'quizzes' has no initializer and is not definitely assigned in the constructor.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:14 
    TS2339: Property 'http' does not exist on type 'QuizListComponent'.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:46 
    TS7006: Parameter 'result' implicitly has an 'any' type.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:83 
    TS7006: Parameter 'error' implicitly has an 'any' type.

Can you help me.   Thank you in advance.

**Comment by JoelTipke** [comment]
What is the actual error you are getting?

**Comment by Borislavsl** [comment]
I'm getting several errors:

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\node_modules\bootstrap\dist\js'
@ ./node_modules/bootstrap/dist/js/bootstrap.js 7:100-120
@ ./ClientApp/boot.browser.ts
@ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in ./ClientApp/boot.browser.ts
Module not found: Error: Can't resolve 'zone.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\ClientApp'
@ ./ClientApp/boot.browser.ts 2:0-17
@ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:10:5

**Comment by diverjasongray** [comment]
This is the error from the stack I am receiving:

NodeInvocationException: Prerendering failed because of error: Error: Cannot find module "@angular/common/http" at Object.<anonymous> (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:17219:7) at __webpack_require__ (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:20:30) at Object.hasOwn (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:15294:77) at __webpack_require__ (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:20:30) at Object.<anonymous> (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:17345:81) at __webpack_require__ (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:20:30) at C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:66:18 at Object.<anonymous> (C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp\ClientApp\dist\main-server.js:69:10) at Module._compile (module.js:649:30) at Object.Module._extensions..js (module.js:660:10) Current directory is: C:\Users\1801\source\repos\TestMakerFree\TestMakerFreeWebApp

**Comment by Darkseal** [comment]
Hello there and thank you for purchasing the book.

Did you try to download the GitHub code  (without modifying it) and see if it builds that way? It could be an issue with some newer versions of the various NPM packages used.

**Comment by Borislavsl** [comment]
Hello,  with GitHub, as I downloaded, it works.   I  upgraded packages (i.e. Angular 5.2.9, and others also), but the result is with errors.  Here is package.json file content:

{
  "name": "TestMakerFreeWebApp",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "devDependencies": {
    "@angular/animations": "5.2.9",
    "@angular/common": "5.2.9",
    "@angular/compiler": "5.2.9",
    "@angular/compiler-cli": "5.2.9",
    "@angular/core": "5.2.9",
    "@angular/forms": "5.2.9",
    "@angular/http": "5.2.9",
    "@angular/platform-browser": "5.2.9",
    "@angular/platform-browser-dynamic": "5.2.9",
    "@angular/platform-server": "5.2.9",
    "@angular/router": "5.2.9",
    "@ngtools/webpack": "6.0.0-rc.2.4",
    "@types/chai": "4.1.2",
    "@types/jasmine": "2.8.6",
    "@types/webpack-env": "1.13.5",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.3",
    "awesome-typescript-loader": "5.0.0",
    "bootstrap": "4.0.0",
    "chai": "4.1.2",
    "css": "2.2.1",
    "css-loader": "0.28.11",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.12",
    "expose-loader": "0.7.5",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.11",
    "html-loader": "0.5.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "3.1.0",
    "jquery": "3.3.1",
    "json-loader": "0.5.7",
    "karma": "2.0.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.1",
    "karma-webpack": "3.0.0",
    "preboot": "6.0.0-beta.3",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.12",
    "rxjs": "5.5.8",
    "style-loader": "0.20.3",
    "to-string-loader": "1.1.5",
    "typescript": "2.8.1",
    "url-loader": "1.0.1",
    "webpack": "4.5.0",
    "webpack-hot-middleware": "2.22.0",
    "webpack-merge": "4.1.2",
    "zone.js": "0.8.26"
  }
}
Is there something missing or wrong?

**Comment by Darkseal** [comment]
I will need some time to check with that Angular version: sadly, as I stated on Chapter 1, upgrading the package is not an option if you're not willing to go through the various change logs and do the minor required steps to adapt the code to the new stuff.

**Comment by Borislavsl** [comment]
Thank you for your answers.   Can you write me the right comands to upgrade both **package.json** file and **npm dependencies**  to the latest (stable) versions of packages.
