### ISSUE TITLE
The New User Registration is not working

### ISSUE THREAD

**Issue by Sami-L** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#3]
Hello,
Git cloned the code from here, then used only the finished project, followed the new book instructions, and then run the initial migrations using the command below from an admin powershell window:

**dotnet ef migrations add "Initial" -o "Data\Migrations"**

Got error: An error occurred while calling method 'BuildWebHost' on class 'Program'. Continuing without the application service provider. **Error: Invalid object name 'Users'.**

Then executed    **dotnet ef database update**

And got the database tables and the sample data. The 4 default users and related stuff are there.

I ensured I can login normally, but when I click to add a new user in the register form, nothing happens and the browser ( Chrome ) console shows the following message:

```
HttpErrorResponse {headers: HttpHeaders, status: 200, statusText: "OK", url: "http://localhost:14600/api/user", ok: false, …}
error

SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at XMLHttpRequest.onLoad (http://localhost:14600/dist/main-client.js?


Then Trying to send the request using Postman

```
{
"username":"User1",
"password":"Pass4User1",
"Email":"d@d.com",
"DisplayName":"User1"
}
```
I get the 500 Internal server error,  with the  next header:

SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_AspNetUserRoles_Users_UserId". The conflict occurred in database "DataBaseName", table "dbo.Users", column 'Id'.
 The statement has been terminated.

I checked and compared the FOREIGN KEY constraint "FK_AspNetUserRoles_Users_UserId" with another working database and found they are same, so I guess the code doesn't provide a default role to the registering user.

**Comment by Darkseal** [comment]
Hello,
Thank you for purchasing the book: there is a mistake in book page 437.

Instead of this:

        /// <summary>
        /// POST: api/user
        /// </summary>
        /// <returns>Creates a new User and return it accordingly.</returns>
        [HttpPost()]
        public async Task<IActionResult> Add([FromBody]UserViewModel model)


There should be this:

        /// <summary>
        /// PUT: api/user
        /// </summary>
        /// <returns>Creates a new User and return it accordingly.</returns>
        [HttpPut()]
        public async Task<IActionResult> Put([FromBody]UserViewModel model)

If you perform this change, you'll be able to register a new user propertly. 

The glitch is also present on GitHub: I'll do my best to have the repo updated accordingly: sorry again for the typo and enjoy the book!

**Comment by Sami-L** [comment]
Thank you,

I changed the "POST" and the "Add" to "Put" as you suggested, but still doesn't work.

This time the error is:

PUT http://localhost:51923/api/user 500 (Internal Server Error)
register.component.ts:68 HttpErrorResponse {headers: HttpHeaders, status: 500, statusText: "Internal Server Error", url: "http://localhost:51923/api/user", ok: false, …}

**Comment by Darkseal** [comment]
I tested Chapter 9 code with these changes and it works, it created the test user and I've also been able to login with it. Try to put a breakpoint into the UserComponent.Put method and see where it crashes and why (tell me the line and the error message).

**Comment by Sami-L** [comment]
Sorry, today, just after starting my computer, I tried it and it worked. I guess the last error was due to the browser cache.

Thanks again.

**Comment by Darkseal** [comment]
Great to hear that: I sincerely hope that you will enjoy the book!

Take care.

**Comment by Belka383** [comment]
In this form for registration, you need to add validators for the password: The password must be 7 or more characters long, contain at least one number, at least one letter in upper case and at least one letter in lowercase. Otherwise nothing happens!

**Comment by Sami-L** [comment]
@Belka383 As you can see above, this was a code error (PUT instead POST), and the author fixed it.

**Comment by Belka383** [comment]
You are right, but even after correcting the error, you can not specify a password that does not fit according to these criteria - nothing will happen! Server Error 500. Check and unsubscribe! 

It is necessary somehow to validate the given parameters (in file Startup.cs): 
                    opts.Password.RequireDigit = true;
                    opts.Password.RequireLowercase = true;
                    opts.Password.RequireUppercase = true;
                    opts.Password.RequireNonAlphanumeric = false;
                    opts.Password.RequiredLength = 7;

**Comment by Sami-L** [comment]
@Belka383 I have tried the case you evocated, and yes, this is an issue.
in addition to that, when the user is logged, the user name should appear in the header as logged in.
Please rise a new separate issue, @Darkseal  should be aware of this.

**Comment by Darkseal** [comment]
Thanks, just answered in Issue #11: master branch has been updated as well with the fix.
