### ISSUE TITLE
ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js Module not found: Error: Can't resolve 'popper.js'

### ISSUE THREAD

**Issue by Borislavsl** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#30]
Hello, When I start Chapter 3 page 113 Testing up, I receive the following errors:

ERROR in ./node_modules/bootstrap/dist/js/bootstrap.js
Module not found: Error: Can't resolve 'popper.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\node_modules\bootstrap\dist\js'
@ ./node_modules/bootstrap/dist/js/bootstrap.js 7:100-120
@ ./ClientApp/boot.browser.ts
@ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in ./ClientApp/boot.browser.ts
Module not found: Error: Can't resolve 'zone.js' in 'D:\MVC\TestMakerFree\TestMakerFreeWebApp\ClientApp'
@ ./ClientApp/boot.browser.ts 2:0-17
@ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts

ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:10:5
TS2564: Property 'selectedQuiz' has no initializer and is not definitely assigned in the constructor.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:11:5
TS2564: Property 'quizzes' has no initializer and is not definitely assigned in the constructor.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:14
TS2339: Property 'http' does not exist on type 'QuizListComponent'.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:46
TS7006: Parameter 'result' implicitly has an 'any' type.
ERROR in [at-loader] ./ClientApp/app/components/quiz/quiz-list.component.ts:15:83
TS7006: Parameter 'error' implicitly has an 'any' type.

Can you help me. Thank you in advance.

**Comment by Darkseal** [comment]
It sounds rather similar to issue #28 : please check GitHub code and confirm that it works. If it does, you'll most likely upgraded your Angular version, hence you'll have to go through a couple change logs and adapt the code accordingly (see Chapter 1 disclaimers on upgrading packagers for details).
