### ISSUE TITLE
Breakpoint will not currently be hit. No symbols loaded for this document (TS code)

### ISSUE THREAD

**Issue by Borislavsl** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#31]
I'm trying to take advantage of the TypeScript runtime debugging capabilities
provided by Visual Studio 2017, as shown in page 124 of the book. But after I start debugging, it shows me on the breakpoint the message:
**Breakpoint will not currently be hit. No symbols loaded for this document**
and  it does not stop at the breakpoint.

Can you help me?  Thank you in advance.

**Comment by Darkseal** [comment]
Hello there: I never experienced such issue, but this thread might help you:
