### ISSUE TITLE
Forgot password & remember me

### ISSUE THREAD

**Issue by jhaacke** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#34]
In the section of the book that covers Login implementation, the text states:

"To be completely honest, the Remember me and Forgot the password? functions are not working yet, but we'll fix those in due time."

However I don't see anywhere in the book where these features are covered. Am I missing something?

**Comment by Darkseal** [comment]
You're right, that part didn't make it in the final cut: I was forced to leave something out to the keep the book within the 550 pages limit. Sadly, that phrase was not edited as it should've been :)
