### ISSUE TITLE
Why Have a Type Property in Token Table?

### ISSUE THREAD

**Issue by chobo2** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#36]
Hi

I am a bit confused on why you have a property called "Type" in your token class. All the book says is

> There's nothing new here, just the minimum amount of properties to store the relevant information about the token: the ClientId, where it comes from, its Type(we'll use a value of zero for refresh tokens), its Value, the UserId it was issued to, and the creation date.

What other types other than a refresh token would be stored in this table?

**Comment by Darkseal** [comment]
I almost always rely on a "Type" int column in my Data Models to leave open the chance of defining a `TokenType` enum class should the need arise (ref. https://tools.ietf.org/html/rfc6749#section-7.1 ). Take it as an old habit of mine.

However, in that specific scenario it's not necessary, so I agree with you that it could be dropped - unless you want to take that sample project further ahead.

**Comment by chobo2** [comment]
Ah I got you, so basically if you decide to change from bearer to something else but I guess your still supporting it you can in theory have a few different types going.
