### ISSUE TITLE
Identity roles doesn't work

### ISSUE THREAD

**Issue by MammadK** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#38]
hello 
I want to use "Role" for "Authorize" in Controller like this
  [Authorize(Roles = "Administrator")]
but it doesn't work.
also when i use this code:
     ApplicationUser user=UserManager.FindByEmailAsync("admin@testmakerfree.com").Result;
            var roles =  UserManager.GetRolesAsync(user);
roles return "null".
i need to use it.
please help me.
thank you.

**Comment by Darkseal** [comment]
Hello there and thank you for purchasing the book. Please answer to the following questions to help me understand and pinpoint your issue:

- Are you 100% sure that you properly seeded the Database following the book Chapter 4? Are you 100% positive that the roles have been created in the Database without significative errors returned by the command prompt?

- Can you confirm that the `Administrator` role is actually present within the `aspnet_Roles` table of the "TestMakerFree" database?

Waiting for your answer.

**Comment by Darkseal** [comment]
Closing, reopen if/when you care to answer.

**Comment by JhonBehan** [comment]
Hi @Darkseal , thanks for the support in the beginning, i got the same issue as MammadK, i cant manage how to add roles based filter upon the contollers for role based authorization. 
Let me explain a little better, for me is working fine the [Authorized] filter but not the [Authorized(Roles="Administrator")] i got the DB seeded right as you can see in the screen shots.
In the book i m greatly guided throught the creation of the registeredUser and the Administrator roles but after does't explain how to get use of those roles for protecting apps API! am i missing something. i really need this!
![users](https://user-images.githubusercontent.com/25555836/45021819-da2c7480-b032-11e8-8225-e23992f32f38.PNG)
![usertoroles](https://user-images.githubusercontent.com/25555836/45021831-ddbffb80-b032-11e8-87f6-d9c52be6ec5e.PNG)
![roles](https://user-images.githubusercontent.com/25555836/45021835-df89bf00-b032-11e8-8423-5f81cc9e69d9.PNG)
as MammadK says i tried to retrive information about the user in as an example the quiz controller here there i a screen shot and everything seems working fine here is the pic. 
![gettingtheusersandroles](https://user-images.githubusercontent.com/25555836/45022606-f4675200-b034-11e8-9a6b-662beafe151a.PNG)
Also i got one last question, roaming around the internet in the various stackoverflow or blogs i find that everyone is putting the policy or role data in the jwt token and then in the startup class somehow setting the built in authorize class to manage policy or roles, but instead can i in someway get the roles of the user based on his Id on the DB? so somehow i can get the roles of the user on the fly and check for right authorization role so i don t have to expose roles of the user to the public?
Well thanks for everything, hope i wrote something understandable!
