### ISSUE TITLE
Test code breaks Chap1 example

### ISSUE THREAD

**Issue by mmcglumphy** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#39]
I've found that removing the following file fixes the Chap01_Part01 example project for me...

ASP.NET-Core-2-and-Angular-5/TestMakerFreeWebApp_Chapter_01_Part01/ClientApp/app/components/counter/counter.component.ts

Initially, I received errors launching the site from this project. Erroneous unit tests?

**Comment by Darkseal** [comment]
Please read book's Chapter 01, paragraph **Client app cleanup** (page 66 & onwards). These components are meant to be deleted, since they're part of the Angular 5 sample project that is used as a "boilerplate" to setup the VS2017 project.

Quoting from that paragraph:

> Now that our server-side journey has come to an end, it's time to challenge ourselves with a quick client-side exercise. Don't worry, it will be just a rather trivial demonstration of how we can update the Angular source code that lies within the /ClientApp/ folder to better suit our needs. More specifically, we will remove all the stuff we don't need from the sample Angular app shipped with our chosen Angular SPA Template and replace them with our own content.

**Comment by mmcglumphy** [comment]
Thanks. Missed that little detail. 

I did purchase and am reading the book. Great all around intro for non-total-beginners. Looking forward to continuing.
