### ISSUE TITLE
Missing change of bootstrap class in book

### ISSUE THREAD

**Issue by edusfc15** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#40]
In all references of the `navmenu.component.html`, in the div of the navbar, the book points to the following class: `navbar-inverse`. But, starting in the page 296 of chapter 6, the component changed the color to dark blue. I found that the class responsible for this is the  `navbar-default`, but at no time quoted in the book.

Maybe this issue can help someone, with the same problem.

**Comment by Darkseal** [comment]
You're right, there's definitely a missing class change in the `navmenu.component.html` file - from `navbar-inverse` to `navbar-default` - in Chapter 06, Page 286 (**Revising the UI Structure** > **NavMenuComponent**).

Luckily enough the correct class update is well-present in the GitHub code, where the NavMenuComponent has the `navbar-inverse` class up to Chapter 5 and the `navbar-default` class from Chapter 06 onwards. 

Unfortunately, such change is not reflected in the book text.
