### ISSUE TITLE
Chapter 9 Async Refresh Token

### ISSUE THREAD

**Issue by elchente23** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#43]
When I make more than one async request to the backend and token is expired I get an error 401 for each request, this causes the creation of a token per request in the table because a request follows the previous one.

There is some way to control this behavior?

**Comment by Darkseal** [comment]
Hello there,
thank you for purchasing the book.

The issue you are referring to has been fixed on January 2018 with a book update:

https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/8
https://github.com/PacktPublishing/ASP.NET-Core-2-and-Angular-5/issues/15

You can already find the updated source code on this GitHub repo. Please let me know if that's enough to fix your scenario as well.
