### ISSUE TITLE
General Controller issue

### ISSUE THREAD

**Issue by idiotsky** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#46]
All the controller should be use Post for Save and Put for Update.
reference to https://stackoverflow.com/questions/630453/put-vs-post-in-rest

**Comment by v2Dark** [comment]
Yes, that was a editing error that was pointed out in late 2017, unfortunately there's yet to be a proper reprint for that.

**Comment by Darkseal** [comment]
Yes, that was a editing error that was pointed out in late 2017, unfortunately there's yet to be a proper reprint for that.
