### ISSUE TITLE
Chapter_08. An unhandled exception occurred while processing the request. 

### ISSUE THREAD

**Issue by Belka383** [PacktPublishing/ASP.NET-Core-2-and-Angular-5#9]
When you run the code from paragraph 8, an error occurs: "An unhandled exception occurred while processing the request. NodeInvocationException: Prerendering timed out after 30000ms because the boot function in 'ClientApp/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper." 

It occurs when you directly use the route "http: // localhost: <port> / home", at direct reference on a route: "http: // localhost: <port> / login" there is no error!

**Comment by Darkseal** [comment]
Hello and thank you for purchasing the book.

I couldn't reproduce your problem but we're aware of the fact that _Server-Side-Rendering_ is partially broken with Angular 5 (treeshaking issues). The .NET Core staff is currently working on a new template to make it work, as you can see here:

https://github.com/aspnet/JavaScriptServices/issues/1385#issuecomment-346647606

Meanwhile, the temporary solution is to remove the SSR (Server Side Rendering). That means opening the `Home/Index.cshtml` file and replace this:

`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`

with this:

`<app>Loading...</app>`

I strongly suggest you to try that and work around with it until the `JavaScriptService` package gets updated. Sorry for the inconvenience.

**Comment by Belka383** [comment]
Using this, rendering takes place. Thanks
